@startuml

title __EXCEPTIONS's Class Diagram__\n

  namespace  {
    namespace xceptions {
      class exceptions.DivideByZeroException {
          {static} - serialVersionUID : long
          + DivideByZeroException()
          + getMessage()
      }
    }
  }
  

  namespace  {
    namespace xceptions {
      class exceptions.DivideByZeroException {
          {static} - serialVersionUID : long
          + DivideByZeroException()
          + getMessage()
      }
    }
  }
  

  namespace  {
    namespace xceptions {
      class exceptions.ExpressionException {
          {static} - serialVersionUID : long
          + ExpressionException()
          + getMessage()
      }
    }
  }
  

  namespace  {
    namespace xceptions {
      class exceptions.ExpressionException {
          {static} - serialVersionUID : long
          + ExpressionException()
          + getMessage()
      }
    }
  }
  

  namespace  {
    namespace xceptions {
      class exceptions.FunctionException {
          {static} - serialVersionUID : long
          + FunctionException()
          + getMessage()
      }
    }
  }
  

  namespace  {
    namespace xceptions {
      class exceptions.FunctionException {
          {static} - serialVersionUID : long
          + FunctionException()
          + getMessage()
      }
    }
  }
  

  namespace  {
    namespace xceptions {
      class exceptions.ParenthesisException {
          {static} - serialVersionUID : long
          + ParenthesisException()
          + getMessage()
      }
    }
  }
  

  namespace  {
    namespace xceptions {
      class exceptions.ParenthesisException {
          {static} - serialVersionUID : long
          + ParenthesisException()
          + getMessage()
      }
    }
  }
  

  namespace  {
    namespace xceptions {
      class exceptions.PostfixException {
          {static} - serialVersionUID : long
          + PostfixException()
          + getMessage()
      }
    }
  }
  

  namespace  {
    namespace xceptions {
      class exceptions.PostfixException {
          {static} - serialVersionUID : long
          + PostfixException()
          + getMessage()
      }
    }
  }
  

  namespace  {
    namespace xceptions {
      class exceptions.TokenizeException {
          ~ str : String
          {static} - serialVersionUID : long
          + TokenizeException()
          + getMessage()
      }
    }
  }
  

  namespace  {
    namespace xceptions {
      class exceptions.TokenizeException {
          ~ str : String
          {static} - serialVersionUID : long
          + TokenizeException()
          + getMessage()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
